/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vfiqxlqhyhpoflcqoddl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmaXF4bHFoeWhwb2ZsY3FvZGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTEyMjQsImV4cCI6MjA3MzI2NzIyNH0.0PYq45875puW-mIfY4BX8irhY1h7-UWjOyAOjrnUDAc"